name: cd-prod

on:
  push:
    branches:
      - check-log

jobs:
  deploy:
    runs-on: prod

    steps:
      - name: springboot log check
        run: |
          cd ~/deploy/2024-mouda/backend && ls && tail -f log.out
