name: cd-prod

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: prod

    steps:
      - name: deploy
        run: |
          cd ~/deploy
          sudo rm -rf 2024-mouda
          git clone https://github.com/woowacourse-teams/2024-mouda.git
          ./deploy.sh
